server:
  port: 8880
spring:
  application:
    name: pretty-cat-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ff1093445004/pretty-cat.git
          username: ff1093445004
          password: ff19871218
          search-paths: config-dev