server:
  port: 8380
spring:
  application:
    name: pretty-cat-scheduler
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8180/eureka/
logging:
  config:
    classpath: log/logback-spring.xml
  path: C:\Users\zhm\Desktop\log