server:
  port: 8480
spring:
  application:
    name: pretty-cat-redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8180/eureka/
