server:
  port: 8580
spring:
  application:
    name: pretty-cat-product
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8180/eureka/
