server:
  port: 8680
spring:
  application:
    name: pretty-cat-api
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8180/eureka/