server:
  port: 8180
spring:
  application:
    name: pretty-cat-eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  instance:
    prefer-ip-address: true